### ISSUE TITLE
incorrect Buffer length

### ISSUE THREAD

**Issue by RudraGupta** [rwb27/openflexure_microscope_software#13]
I installed the software but when I run it i get below error and it stops:
PiCameraValueError: Incorrect buffer length for resolution 1640x1232

This is same with V1 and V2 cams.

Ps, the preview shows up when the program is run

**Comment by RudraGupta** [comment]
Forgot to mentions. This is happening when i run recalibrate command:
openflexure_microscope --recalibrate

**Comment by rwb27** [comment]
Hello, firstly I should say this is the old version of the software, and new development is on gitlab. See openflexure.org for links to new and improved software, compete with decent installation instructions. 

I've not seen that message before, but my suspicion is that something has gone wrong setting up the camera sensor mode, or that you have too little GPU RAM. I find strange things happen unless I allocate 256mb to the GPU. This is clarified in the new installation script. 

Thanks 

Richard

**Comment by RudraGupta** [comment]
Thanks Richard. I will try it out and let you know.
